### ISSUE TITLE
源代码符号错误

### ISSUE THREAD

**Issue by fantasticit** [lucefer/webgl#1]
见：https://github.com/lucefer/webgl/blob/master/utils/geometry.js

![image](https://user-images.githubusercontent.com/26452939/53163827-e5d41d80-3609-11e9-9610-8851a6bf6d1d.png)

**Comment by lucefer** [comment]
感谢指正哈

**Comment by fantasticit** [comment]
:) 也感谢你出的这份 gl 教程，等你完善。
